# Generated by Django 4.1 on 2022-09-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0003_order_customer_order_date_created_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_App.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_App.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='skus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Web_App.sku'),
        ),
    ]
