# Generated by Django 4.1 on 2022-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_rename_images_image_image_rename_sizes_sku_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.JSONField()),
            ],
        ),
    ]
