# Generated by Django 4.1 on 2022-09-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0006_viewproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewProduct',
        ),
    ]
